### ISSUE TITLE
How to fit 3D Dress to Human Body from Live Camera ?

### ISSUE THREAD

**Issue by selvakarna** [chaitanya100100/TailorNet#21]
How to fit 3D Dress to Human Body from Live Camera ?

any idea about mkaing 3D Dress and fit to live Human body ? share any idea , Model for 3D Dress making and fit to Human Body?
Like Virtual Dress Fit?

**Comment by chaitanya100100** [comment]
The problems you are mentioning are active research direction with no perfect solutions. Many solutions with various limiting assumptions have been proposed. You can look into some of the works at [here](https://virtualhumans.mpi-inf.mpg.de/publications.html) and [here](http://gvv.mpi-inf.mpg.de/GVV_Projects.html).
Closing the issue since it is not related to this repository.
