### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)

### ISSUE THREAD

**Issue by aapatre** [chaitanya100100/TailorNet#27]
![Screenshot from 2021-03-18 11-52-25](https://user-images.githubusercontent.com/20199688/111582180-7a58dc00-87e0-11eb-849e-410f68daf654.png)

So this happens while using weights & data for male shirt. Female/Male tshirt, Male Short Pants work absolutely fine.

**Comment by chaitanya100100** [comment]
It seems like CUDA issue rather than the weights. Have you tried these solutions: [link 1](https://github.com/huggingface/transformers/issues/6263) and [link 2](https://stackoverflow.com/questions/61473330/cuda-error-cublas-status-alloc-failed-when-calling-cublascreatehandle) ?. Shirt is the garment with the highest number of vertices. So there may be GPU memory issues. What is your GPU memory size?

**Comment by aapatre** [comment]
Yeah, It seems to be a GPU memory issue since we have a 4GB 1650Ti. I tried removing the cuda() calls from [L98](https://github.com/chaitanya100100/TailorNet/blob/62de3c947e7ceaed446b7e40915ec033c7cd55cf/run_tailornet.py#L98), [L99](https://github.com/chaitanya100100/TailorNet/blob/62de3c947e7ceaed446b7e40915ec033c7cd55cf/run_tailornet.py#L99), [L100](https://github.com/chaitanya100100/TailorNet/blob/62de3c947e7ceaed446b7e40915ec033c7cd55cf/run_tailornet.py#L100), in run_tailornet.py and it displays a "CUDA out of memory" error now.

**Comment by chaitanya100100** [comment]
So removing those .cuda() calls won't help because TailorNet model is hardcoded to run on GPU. See [this](https://github.com/chaitanya100100/TailorNet/blob/62de3c947e7ceaed446b7e40915ec033c7cd55cf/models/tailornet_model.py#L54) line. You can remove such calls to run on CPU. Or you can make GPU unavailable for this particular command by setting CUDA_VISIBLE_DEVICES empty.

**Comment by aapatre** [comment]
Thanks a lot for your response @chaitanya100100 
I will check... Apologies for the late reply.
