### ISSUE TITLE
neutral model to gendered model

### ISSUE THREAD

**Issue by mfikryrizal** [chaitanya100100/TailorNet#30]
Hi, I use a human mesh reconstruction tool that infers based on the SMPL neutral model. Is there any way that I can convert the parameters to fit the gendered model(s) that is used by Tailornet?

**Comment by chaitanya100100** [comment]
Pose parameters(theta) are same for neutral and gendered SMPL model. Shape parameters(beta) are specific.
I am not aware of any other public method that does the conversion that you ask.
However, there is an adhoc way. TailorNet deals with only first two shape parameters. First parameter usually deals with height and second parameter deals with width of the body. So one can define some heuristic to transfer beta parameters from neutral to gendered male or female model (by observation and trial and error).
Closing the issue since it's out of scope of this repository.
