### ISSUE TITLE
Missing SMPL models

### ISSUE THREAD

**Issue by juch001** [chaitanya100100/TailorNet#31]
Hi, from the code, it requires the following SMPL models. but cannot find them. could you please upload them? thanks.

SMPL_PATH_NEUTRAL = '/BS/RVH/work/data/smpl_models/neutral/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl'
SMPL_PATH_MALE = '/BS/RVH/work/data/smpl_models/lrotmin/lbs_tj10smooth6_0fixed_normalized/male/model.pkl'
SMPL_PATH_FEMALE = '/BS/RVH/work/data/smpl_models/lrotmin/lbs_tj10smooth6_0fixed_normalized/female/model.pkl'

**Comment by chaitanya100100** [comment]
Follow this link: https://github.com/zycliao/TailorNet_dataset#smpl-model
You will have to register at official SMPL website and then download.

**Comment by juch001** [comment]
I have downloaded the SMPL_python_v.1.0.0.zip, but inside the folder, only has male and female model. No neutral. Where can I get the  neutral model? Thanks.

**Comment by chaitanya100100** [comment]
TailorNet is only available for male and female model. So you don't need neutral model.

**Comment by hbwanghang** [comment]
Hi,I reproduced your code according to your idea, and the result appeared such an error. What is the cause of this error because I did not complete the model training? 
![image](https://user-images.githubusercontent.com/20834302/116017584-97e85380-a672-11eb-83cd-876e38528b89.png)
And when I follow the steps to train the model, this error will be reported. What should I do? 
![image](https://user-images.githubusercontent.com/20834302/116017636-c49c6b00-a672-11eb-89b8-13de5c088903.png)
