### ISSUE TITLE
difference for 'f' and 'ft'. and difference for .obj and .pkl file

### ISSUE THREAD

**Issue by juch001** [chaitanya100100/TailorNet#37]
Hi,

could you please advise what is the difference for 'f' and 'ft' for garment mesh and how to get the 'ft'? 

for same garment mesh, what should i do to get the .pkl file from .obj file. thanks.

**Comment by chaitanya100100** [comment]
ft contains a triplet numbers for each vertex specifying the indices of texture coordinates for the 3 vertices of that face.
See [this](https://www.cs.cmu.edu/~mbz/personal/graphics/obj.html) to learn about the texture coordinate. 
In short,
f v1/vt1 v2/vt2 v3/vt3 is equal to
f v1 v2 v3
ft vt1 vt2 vt3

I have already written on how to use texture: https://github.com/chaitanya100100/TailorNet/issues/36

Why do you need pkl from obj? obj is 3D object format and pkl is file format for serialized python variables. Both exists for different purposes.

**Comment by juch001** [comment]
Hi,

Thank you so much for your reply.

I need the .pkl file as an init template for training. Do you have the
template .pkl files for the garments used in this paper? Thanks so much.

Best regards,
JC

**Comment by chaitanya100100** [comment]
Sorry but I still don't get why do you need pkl file. The pkl files we use are for SMPL body template and some TailorNet metadata. They are mentioned here- https://github.com/chaitanya100100/TailorNet/blob/master/global_var.py
You can download them when you download SMPL body model and TailorNet dataset. 'garment_class_info.pkl' contains details about each garment, in particular, which SMPL body vertices belong to the template garment.

**Comment by juch001** [comment]
Hi,

A sample shirts.pkl file is attached with the corresponding .obj file,
vt_ft file and the vert_indices in gar_file. What I want is to get a
corresponding .pkl template for the garment mesh (the example .pkl file is
an asset file with 8168 vertices for t-shirt). I tried to extract the
shirts.pkl file for your t-shirt garment template, but still cannot find
how to get it.

All the .pkl files are python2 files. Please kindly take a look and see if
you have the related information. Thanks so much.

Best Regards,
JC

**Comment by chaitanya100100** [comment]
I am sorry but I still can't understand your terminology. The way TailorNet works is that SMPL comes with full body template. gar_file contains vert_indices for each garment which means that when you do vertices[shirt_indices], you will get a template (a cut out of the body) for shirt. In our dataset(https://github.com/zycliao/TailorNet_dataset), we give these indices for all garments. TailorNet outputs displacements on these cutout template. Note that texture is out of scope of this repo and you will have to set texture coordinates from MGN repo yourself.

If you still have doubt, can you please be more thorough in your naming conventions. In particular, can you explain...
- What is shirts.pkl file and what arrays and dictionary it contains? And why do you need that?
- What do you mean by vt_ft file?
- When you say .obj file, which file do you mean? .obj file is very vague because it is just a file format for all 3D objects.
- .pkl files are NOT python2 specific. They can work in python3 also.
