### ISSUE TITLE
.ply file as an input ?

### ISSUE THREAD

**Issue by Mohamed-Fathy-Salah** [chaitanya100100/TailorNet#47]
i am having an issue getting it working with a .ply file [output from another model](https://github.com/1900zyh/3D-Human-Body-Shape)
![Screenshot_2021-12-04 Creators 3D Online 3D Viewer](https://user-images.githubusercontent.com/60598620/144719776-cbc8fca4-a0e4-471e-813e-2c0bea47672a.png)
is it possible to use a .ply file instead of theta , beta ? 
if not . can you please guide us ?
thank you.

**Comment by omarmohamed101** [comment]
i'm having the same issue any help please?

**Comment by chaitanya100100** [comment]
TailorNet is trained to take theta, beta and gamma(garment style) as input. So it is not in the scope of this project. However, I will try to give a general idea on how to get theta, beta from any mesh. 

You can get theta and beta for any mesh (.ply file) using a simple optimization. You can optimize to find the theta and beta for which the generated SMPL body closely aligns with your mesh. This general approach is called '3D registration'.

https://github.com/bharat-b7/IPNet/blob/master/smpl_registration/fit_SMPL.py

^ This file has some relevant code. It can fit SMPL body to any scan (even if they don't share the same topology). If your ply file is SMPL body (not just any general mesh) then your loss function should be even simpler (since there is one-to-one correspondence between the SMPL body and your mesh you are trying to fit).
