### ISSUE TITLE
I use VIBE to get theatas and betas from a video and input them to tailornet to get garment, but why the garment 's equality is very bad? Is there any process before input to tailornet? 

### ISSUE THREAD

**Issue by wells-wei-wei** [chaitanya100100/TailorNet#7]

**Comment by chaitanya100100** [comment]
If you use correct parameters within reasonable limit, it should produce plausible garment.

Can you provide the parameters on which the garment is bad? Specifically, gender, garment class, thetas, betas and gammas(garment style).

**Comment by wells-wei-wei** [comment]
> If you use correct parameters within reasonable limit, it should produce plausible garment.
> 
> Can you provide the parameters on which the garment is bad? Specifically, gender, garment class, thetas, betas and gammas(garment style).

I know what happened. Maybe the VIBE‘s coordinate systems is diferent from opengl, the smpl model obtained from VIBE is upside down, so it affected the prediction of pred_verts_d. The function theta_normalized is to rotate the smpl model along y axis so that root rotation can always face the camera right? So it means that only the smpl model face the camera, the prediction of pred_verts_d will be right. Therefore I delete the function normalize_y_rotation but just change the root rotation to [0,0,0] and input tn_runner, then the result is excellent.

**Comment by chaitanya100100** [comment]
Glad that it worked out finally. 

normalize_y_rotation will just make it face the front camera (by eliminating y rotation). However, it can't handle the inverted poses because they are not _natural_ poses. Making the root rotation [0,0,0] might eliminate some required information also. So instead, you can rotate 180 degree about x or z axis to make it upright position and then use normalize_y_rotation to make it face frontal camera. It would also work.

**Comment by CrossLee1** [comment]
VIBE can predicts the theatas and betas of a sequence, but it is not the groundtruth theatas and betas.
How to get the correct groundtruth theatas and betas sequence?

**Comment by melih1996** [comment]
@wells-wei-wei how did you solve the problem of being upside down?
